In [41]:
import pandas as pd

# reading csv file
df = pd.read_csv(r"D:\harsh attrishi\data analysis projects\ecommerce-sales-analysis\raw data\messy_ecommerce_data.csv")

In [42]:
# checking info about dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order ID         300 non-null    str
 1   Order Date       300 non-null    str
 2   Customer Name    259 non-null    str
 3   Product_ Name    300 non-null    str
 4   Category Name    249 non-null    str
 5   QTY              264 non-null    float64
 6    Unit Price ($)  251 non-null    float64
 7   PAYMENT_MODE     249 non-null    str
 8   Is_Shipped       245 non-null    str
 9   Review Rating    252 non-null    float64
dtypes: float64(3), str(7)
memory usage: 23.6 KB

In [43]:
# checking and cleaning colums

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['order_id', 'order_date', 'customer_name', 'product__name',
       'category_name', 'qty', 'unit_price_($)', 'payment_mode', 'is_shipped',
       'review_rating'],
      dtype='str')

In [44]:
# checking null values

df.isnull().sum()

order_id           0
order_date         0
customer_name     41
product__name      0
category_name     51
qty               36
unit_price_($)    49
payment_mode      51
is_shipped        55
review_rating     48
dtype: int64

In [45]:
# checking shape 

df.shape

(300, 10)

In [46]:
# dropping duplicate

df = df.drop_duplicates()
df.shape # 5 lines of code is been dropped

(295, 10)

In [47]:
# filling missing values in review rating

df["review_rating"] = df["review_rating"].fillna(2.5) # a avg rating

# checking did it worked or not

df.isnull().sum()

order_id           0
order_date         0
customer_name     40
product__name      0
category_name     49
qty               35
unit_price_($)    49
payment_mode      50
is_shipped        54
review_rating      0
dtype: int64

In [48]:
# cleaning string values

df["customer_name"] = df["customer_name"].str.lower().str.strip().str.replace(" " , "_")
df["payment_mode"] = df["payment_mode"].str.lower().str.strip().str.replace(" " , "_")
df["is_shipped"] = df["is_shipped"].str.lower().str.strip().str.replace(" " , "_")
df["category_name"] = df["category_name"].str.lower().str.strip().str.replace(" " , "_")

df.head(20)

,order_id,order_date,customer_name,product__name,category_name,qty,unit_price_($),payment_mode,is_shipped,review_rating
0,ORD_1203,2026-05-16,alice_smith,usb-c cable,elec.,3.0,99.99,credit_card,no,2.5
1,ORD_1266,2026-01-16,alice_smith,usb-c cable,accessories,1.0,699.99,credit_card,yes,1.0
2,ORD_1152,2026-06-24,alice_smith,laptop Pro,accessories,5.0,99.99,crypto,no,2.0
3,ORD_1009,2026-05-20,NaN,Smart Watch,computers,5.0,-45.00,NaN,yes,1.0
4,ORD_1233,2026-02-28,bob_johnson,wireless mouse,NaN,2.0,29.99,paypal,no,2.5
5,ORD_1226,2026-02-28,NaN,iPhone 15,accessories,NaN,-45.00,credit_card,NaN,3.0
6,ORD_1196,2026-02-02,bob_johnson,wireless mouse,computers,5.0,NaN,cash,yes,2.0
7,ORD_1109,2026-03-22,emma_w.,Smart Watch,accessories,1.0,699.99,crypto,n,99.0
8,ORD_1005,2026-02-27,alice_smith,wireless mouse,electronics,3.0,29.99,cash,yes,2.0
9,ORD_1175,2026-04-06,NaN,headPHONES,elec.,4.0,-45.00,paypal,n,4.0
10,ORD_1237,2026-01-19,NaN,headPHONES,computers,NaN,29.99,NaN,yes,99.0
11,ORD_1057,2026-06-08,alice_smith,usb-c cable,accessories,4.0,29.99,credit_card,n,5.0
12,ORD_1218,2026-01-31,NaN,iPhone 15,accessories,4.0,NaN,cash,no,4.0
13,ORD_1045,2026-03-30,alice_smith,usb-c cable,accessories,2.0,NaN,credit_card,yes,3.0
14,ORD_1182,2026-05-06,alice_smith,headPHONES,accessories,100.0,1099.99,cash,yes,99.0
15,ORD_1221,2026-01-17,bob_johnson,LAPTOP PRO,elec.,10.0,99.99,paypal,no,99.0
16,ORD_1289,2026-01-24,david_g.,Smart Watch,computers,10.0,99.99,crypto,NaN,99.0
17,ORD_1211,2026-04-13,bob_johnson,Smart Watch,electronics,2.0,99.99,credit_card,yes,3.0
18,ORD_1148,2026-05-22,emma_w.,Smart Watch,accessories,3.0,-45.00,NaN,NaN,4.0
19,ORD_1165,2026-02-15,charlie_brown,iPhone 15,electronics,5.0,699.99,NaN,NaN,5.0

In [49]:
# replacing 99.0 value with 5 in review rating

df["review_rating"] = df["review_rating"].replace(99.0,5)

# filling nan value in payment mode with cash

df["payment_mode"] = df["payment_mode"].fillna("cash")

# replacing nan values into " "

df["qty"] = df["qty"].fillna(0)

# replacing category name into accessories for nan values

df["category_name"] = df["category_name"].fillna("accessories")

In [50]:
# droping negative values in price

# 1. Find the rows where price is negative
negative_prices_index = df[df["unit_price_($)"] < 0].index

# 2. Drop them using their index labels
df = df.drop(negative_prices_index)


df.sample(20)

,order_id,order_date,customer_name,product__name,category_name,qty,unit_price_($),payment_mode,is_shipped,review_rating
120,ORD_1055,2026-03-17,david_g.,headPHONES,accessories,3.0,29.99,credit_card,yes,5.0
188,ORD_1098,2026-06-25,bob_johnson,iPhone 15,accessories,3.0,NaN,credit_card,yes,3.0
104,ORD_1265,2026-01-26,david_g.,LAPTOP PRO,electronics,1.0,1099.99,credit_card,NaN,2.0
298,ORD_1270,2026-03-05,charlie_brown,LAPTOP PRO,accessories,4.0,699.99,credit_card,yes,2.5
229,ORD_1212,2026-06-21,NaN,Smart Watch,elec.,100.0,699.99,paypal,no,3.0
59,ORD_1025,2026-05-20,alice_smith,wireless mouse,electronics,100.0,1099.99,crypto,no,2.5
14,ORD_1182,2026-05-06,alice_smith,headPHONES,accessories,100.0,1099.99,cash,yes,5.0
111,ORD_1262,2026-06-22,charlie_brown,laptop Pro,accessories,100.0,1099.99,cash,no,1.0
180,ORD_1200,2026-05-21,emma_w.,LAPTOP PRO,electronics,2.0,NaN,cash,no,2.5
259,ORD_1034,2026-04-19,david_g.,LAPTOP PRO,accessories,2.0,29.99,credit_card,yes,5.0
87,ORD_1072,2026-04-27,charlie_brown,LAPTOP PRO,electronics,10.0,29.99,paypal,yes,5.0
42,ORD_1286,2026-06-16,alice_smith,Smart Watch,accessories,1.0,99.99,cash,no,5.0
219,ORD_1040,2026-01-27,alice_smith,LAPTOP PRO,accessories,0.0,699.99,cash,n,4.0
148,ORD_1029,2026-05-31,alice_smith,headPHONES,accessories,5.0,29.99,cash,yes,3.0
277,ORD_1058,2026-04-03,david_g.,wireless mouse,electronics,3.0,NaN,credit_card,n,3.0
271,ORD_1050,2026-05-18,bob_johnson,usb-c cable,accessories,0.0,699.99,credit_card,yes,1.0
49,ORD_1231,2026-06-11,alice_smith,LAPTOP PRO,accessories,5.0,1099.99,credit_card,NaN,2.5
182,ORD_1268,2026-03-28,david_g.,Smart Watch,accessories,4.0,699.99,crypto,no,2.0
30,ORD_1017,2026-03-01,david_g.,laptop Pro,accessories,2.0,NaN,cash,no,3.0
272,ORD_1174,2026-02-09,NaN,headPHONES,elec.,10.0,99.99,crypto,n,2.0

In [51]:
# cleaned unit price 

missing_values_df = df[df["unit_price_($)"].isna()]

df = df.drop(missing_values_df.index)
 
# missing_values_df.to_csv("null_prices_index.csv" )

In [52]:
# cleaning is shipped

df["is_shipped"] = df["is_shipped"].replace("n" , "no")

df["is_shipped"] = df["is_shipped"].fillna("no")

In [53]:
# finnally dropping data of unknown person so we can focus on this clean data

df = df.dropna()

# df.to_csv("cleaned_ecommerce_data.csv" , index=False)

# rate this cleaning process out of 10