In [162]:
import pandas as pd

# reading csv file
df = pd.read_csv("messy_ecommerce_data.csv")

In [163]:
# checking info about dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order ID         300 non-null    str
 1   Order Date       300 non-null    str
 2   Customer Name    259 non-null    str
 3   Product_ Name    300 non-null    str
 4   Category Name    249 non-null    str
 5   QTY              264 non-null    float64
 6    Unit Price ($)  251 non-null    float64
 7   PAYMENT_MODE     249 non-null    str
 8   Is_Shipped       245 non-null    str
 9   Review Rating    252 non-null    float64
dtypes: float64(3), str(7)
memory usage: 23.6 KB

In [164]:
# checking and cleaning colums

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['order_id', 'order_date', 'customer_name', 'product__name',
       'category_name', 'qty', 'unit_price_($)', 'payment_mode', 'is_shipped',
       'review_rating'],
      dtype='str')

In [165]:
# checking null values

df.isnull().sum()

order_id           0
order_date         0
customer_name     41
product__name      0
category_name     51
qty               36
unit_price_($)    49
payment_mode      51
is_shipped        55
review_rating     48
dtype: int64

In [166]:
# checking shape 

df.shape

(300, 10)

In [167]:
# dropping duplicate

df = df.drop_duplicates()
df.shape # 5 lines of code is been dropped

(295, 10)

In [168]:
# filling missing values in review rating

df["review_rating"] = df["review_rating"].fillna(2.5) # a avg rating

# checking did it worked or not

df.isnull().sum()

order_id           0
order_date         0
customer_name     40
product__name      0
category_name     49
qty               35
unit_price_($)    49
payment_mode      50
is_shipped        54
review_rating      0
dtype: int64

In [169]:
# cleaning string values

df["customer_name"] = df["customer_name"].str.lower().str.strip().str.replace(" " , "_")
df["payment_mode"] = df["payment_mode"].str.lower().str.strip().str.replace(" " , "_")
df["is_shipped"] = df["is_shipped"].str.lower().str.strip().str.replace(" " , "_")
df["category_name"] = df["category_name"].str.lower().str.strip().str.replace(" " , "_")

df.head(20)

,order_id,order_date,customer_name,product__name,category_name,qty,unit_price_($),payment_mode,is_shipped,review_rating
0,ORD_1203,2026-05-16,alice_smith,usb-c cable,elec.,3.0,99.99,credit_card,no,2.5
1,ORD_1266,2026-01-16,alice_smith,usb-c cable,accessories,1.0,699.99,credit_card,yes,1.0
2,ORD_1152,2026-06-24,alice_smith,laptop Pro,accessories,5.0,99.99,crypto,no,2.0
3,ORD_1009,2026-05-20,NaN,Smart Watch,computers,5.0,-45.00,NaN,yes,1.0
4,ORD_1233,2026-02-28,bob_johnson,wireless mouse,NaN,2.0,29.99,paypal,no,2.5
5,ORD_1226,2026-02-28,NaN,iPhone 15,accessories,NaN,-45.00,credit_card,NaN,3.0
6,ORD_1196,2026-02-02,bob_johnson,wireless mouse,computers,5.0,NaN,cash,yes,2.0
7,ORD_1109,2026-03-22,emma_w.,Smart Watch,accessories,1.0,699.99,crypto,n,99.0
8,ORD_1005,2026-02-27,alice_smith,wireless mouse,electronics,3.0,29.99,cash,yes,2.0
9,ORD_1175,2026-04-06,NaN,headPHONES,elec.,4.0,-45.00,paypal,n,4.0
10,ORD_1237,2026-01-19,NaN,headPHONES,computers,NaN,29.99,NaN,yes,99.0
11,ORD_1057,2026-06-08,alice_smith,usb-c cable,accessories,4.0,29.99,credit_card,n,5.0
12,ORD_1218,2026-01-31,NaN,iPhone 15,accessories,4.0,NaN,cash,no,4.0
13,ORD_1045,2026-03-30,alice_smith,usb-c cable,accessories,2.0,NaN,credit_card,yes,3.0
14,ORD_1182,2026-05-06,alice_smith,headPHONES,accessories,100.0,1099.99,cash,yes,99.0
15,ORD_1221,2026-01-17,bob_johnson,LAPTOP PRO,elec.,10.0,99.99,paypal,no,99.0
16,ORD_1289,2026-01-24,david_g.,Smart Watch,computers,10.0,99.99,crypto,NaN,99.0
17,ORD_1211,2026-04-13,bob_johnson,Smart Watch,electronics,2.0,99.99,credit_card,yes,3.0
18,ORD_1148,2026-05-22,emma_w.,Smart Watch,accessories,3.0,-45.00,NaN,NaN,4.0
19,ORD_1165,2026-02-15,charlie_brown,iPhone 15,electronics,5.0,699.99,NaN,NaN,5.0

In [170]:
# replacing 99.0 value with 5 in review rating

df["review_rating"] = df["review_rating"].replace(99.0,5)

# filling nan value in payment mode with cash

df["payment_mode"] = df["payment_mode"].fillna("cash")

# replacing nan values into " "

df["qty"] = df["qty"].fillna(0)

# replacing category name into accessories for nan values

df["category_name"] = df["category_name"].fillna("accessories")

In [171]:
# droping negative values in price

# 1. Find the rows where price is negative
negative_prices_index = df[df["unit_price_($)"] < 0].index

# 2. Drop them using their index labels
df = df.drop(negative_prices_index)


df.sample(20)

,order_id,order_date,customer_name,product__name,category_name,qty,unit_price_($),payment_mode,is_shipped,review_rating
175,ORD_1244,2026-05-19,alice_smith,iPhone 15,electronics,100.0,NaN,credit_card,n,1.0
257,ORD_1080,2026-03-10,NaN,LAPTOP PRO,computers,0.0,NaN,crypto,n,3.0
102,ORD_1031,2026-01-02,charlie_brown,Smart Watch,elec.,5.0,NaN,credit_card,no,4.0
93,ORD_1224,2026-05-31,charlie_brown,LAPTOP PRO,accessories,100.0,NaN,credit_card,NaN,3.0
21,ORD_1113,2026-04-12,emma_w.,LAPTOP PRO,elec.,4.0,99.99,crypto,yes,2.5
101,ORD_1069,2026-01-26,emma_w.,headPHONES,accessories,100.0,1099.99,crypto,yes,2.0
75,ORD_1282,2026-04-24,emma_w.,headPHONES,elec.,3.0,NaN,paypal,no,1.0
171,ORD_1208,2026-06-26,NaN,headPHONES,elec.,0.0,99.99,crypto,yes,5.0
214,ORD_1264,2026-06-15,david_g.,laptop Pro,computers,4.0,29.99,cash,NaN,5.0
129,ORD_1283,2026-05-21,bob_johnson,laptop Pro,accessories,2.0,99.99,crypto,yes,2.5
187,ORD_1171,2026-05-10,alice_smith,Smart Watch,accessories,100.0,29.99,cash,yes,5.0
15,ORD_1221,2026-01-17,bob_johnson,LAPTOP PRO,elec.,10.0,99.99,paypal,no,5.0
166,ORD_1284,2026-01-26,charlie_brown,wireless mouse,computers,1.0,99.99,cash,NaN,5.0
215,ORD_1064,2026-06-19,david_g.,iPhone 15,accessories,1.0,1099.99,credit_card,yes,4.0
144,ORD_1210,2026-03-21,charlie_brown,laptop Pro,computers,5.0,99.99,cash,NaN,2.5
41,ORD_1076,2026-04-05,emma_w.,usb-c cable,elec.,4.0,NaN,cash,n,2.0
252,ORD_1133,2026-01-13,david_g.,headPHONES,electronics,3.0,29.99,paypal,no,5.0
177,ORD_1026,2026-04-18,david_g.,wireless mouse,accessories,100.0,1099.99,credit_card,no,3.0
85,ORD_1114,2026-06-14,alice_smith,Smart Watch,electronics,2.0,99.99,cash,NaN,1.0
184,ORD_1100,2026-01-15,NaN,laptop Pro,computers,100.0,1099.99,cash,yes,5.0

In [172]:
# cleaned unit price 

missing_values_df = df[df["unit_price_($)"].isna()]

df = df.drop(missing_values_df.index)
 
missing_values_df.to_csv("null_prices_index.csv" )

In [173]:
# cleaning is shipped

df["is_shipped"] = df["is_shipped"].replace("n" , "no")

df["is_shipped"] = df["is_shipped"].fillna("no")

In [174]:
# finnally dropping data of unknown person so we can focus on this clean data

df = df.dropna()

df.to_csv("cleaned_ecommerce_data.csv" , index=False)

# rate this cleaning process out of 10